### ISSUE TITLE
Como fazer um Pull Request?

### ISSUE THREAD

**Issue by laccan** [SensorNet-UFAL/docs#1]
Criar a Wiki do *docs* explicando porquê é necessário fazer Push usando Pull Requests, fazendo referência ao git book(https://git-scm.com/book/pt-br/v2) e, à linguagem de marcação do github(https://guides.github.com/features/mastering-markdown/).

**Comment by quindai** [comment]
Terminado, alterações subsequentes serão seguidas de outras issues ou reabertura dessa.
